/*
Question:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

// Approach:
// Since perform XOR twice with the same number cancels the effect, we can XOR a number with all chars in s and t and the remaining value will be the different char

class Solution {
    public char findTheDifference(String s, String t) {
        int c = 0;
        for(char ch: s.toCharArray())c ^= ch;
        for(char ch: t.toCharArray())c ^= ch;
        return (char)c;
    }
}
