/*
Question:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

// Approach:
// Since perform XOR twice with the same number cancels the effect, we can XOR a number with all chars in s and t and the remaining value will be the different char

impl Solution {
    pub fn find_the_difference(s: String, t: String) -> char {
        let mut c = 0;
        for ch in s.chars() {c ^= ch as u8}
        for ch in t.chars() {c ^= ch as u8}
        c as char
    }
}
